//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Clients_ThuVien.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceQLThuVienSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceQLThuVien : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LayDanhSachNXBOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemNXBOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuaNXBOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaNXBOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimKiemNXBOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayDanhSachTacGiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemTGOperationCompleted;
        
        private System.Threading.SendOrPostCallback SuaTGOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaTGOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimKiemTGOperationCompleted;
        
        private System.Threading.SendOrPostCallback PhieuMuonOperationCompleted;
        
        private System.Threading.SendOrPostCallback TinhTrangMuonOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayTenBanDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback LayMaBanDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback KTPhieuMuonOperationCompleted;
        
        private System.Threading.SendOrPostCallback DangNhapOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceQLThuVien() {
            this.Url = global::Clients_ThuVien.Properties.Settings.Default.Clients_ThuVien_localhost_ServiceQLThuVien;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LayDanhSachNXBCompletedEventHandler LayDanhSachNXBCompleted;
        
        /// <remarks/>
        public event ThemNXBCompletedEventHandler ThemNXBCompleted;
        
        /// <remarks/>
        public event SuaNXBCompletedEventHandler SuaNXBCompleted;
        
        /// <remarks/>
        public event XoaNXBCompletedEventHandler XoaNXBCompleted;
        
        /// <remarks/>
        public event TimKiemNXBCompletedEventHandler TimKiemNXBCompleted;
        
        /// <remarks/>
        public event LayDanhSachTacGiaCompletedEventHandler LayDanhSachTacGiaCompleted;
        
        /// <remarks/>
        public event ThemTGCompletedEventHandler ThemTGCompleted;
        
        /// <remarks/>
        public event SuaTGCompletedEventHandler SuaTGCompleted;
        
        /// <remarks/>
        public event XoaTGCompletedEventHandler XoaTGCompleted;
        
        /// <remarks/>
        public event TimKiemTGCompletedEventHandler TimKiemTGCompleted;
        
        /// <remarks/>
        public event PhieuMuonCompletedEventHandler PhieuMuonCompleted;
        
        /// <remarks/>
        public event TinhTrangMuonCompletedEventHandler TinhTrangMuonCompleted;
        
        /// <remarks/>
        public event LayTenBanDocCompletedEventHandler LayTenBanDocCompleted;
        
        /// <remarks/>
        public event LayMaBanDocCompletedEventHandler LayMaBanDocCompleted;
        
        /// <remarks/>
        public event KTPhieuMuonCompletedEventHandler KTPhieuMuonCompleted;
        
        /// <remarks/>
        public event DangNhapCompletedEventHandler DangNhapCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDanhSachNXB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LayDanhSachNXB() {
            object[] results = this.Invoke("LayDanhSachNXB", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LayDanhSachNXBAsync() {
            this.LayDanhSachNXBAsync(null);
        }
        
        /// <remarks/>
        public void LayDanhSachNXBAsync(object userState) {
            if ((this.LayDanhSachNXBOperationCompleted == null)) {
                this.LayDanhSachNXBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDanhSachNXBOperationCompleted);
            }
            this.InvokeAsync("LayDanhSachNXB", new object[0], this.LayDanhSachNXBOperationCompleted, userState);
        }
        
        private void OnLayDanhSachNXBOperationCompleted(object arg) {
            if ((this.LayDanhSachNXBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDanhSachNXBCompleted(this, new LayDanhSachNXBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemNXB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ThemNXB(string ten, string diaChi, string email) {
            object[] results = this.Invoke("ThemNXB", new object[] {
                        ten,
                        diaChi,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ThemNXBAsync(string ten, string diaChi, string email) {
            this.ThemNXBAsync(ten, diaChi, email, null);
        }
        
        /// <remarks/>
        public void ThemNXBAsync(string ten, string diaChi, string email, object userState) {
            if ((this.ThemNXBOperationCompleted == null)) {
                this.ThemNXBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemNXBOperationCompleted);
            }
            this.InvokeAsync("ThemNXB", new object[] {
                        ten,
                        diaChi,
                        email}, this.ThemNXBOperationCompleted, userState);
        }
        
        private void OnThemNXBOperationCompleted(object arg) {
            if ((this.ThemNXBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemNXBCompleted(this, new ThemNXBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuaNXB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SuaNXB(int id, string ten, string diaChi, string email) {
            object[] results = this.Invoke("SuaNXB", new object[] {
                        id,
                        ten,
                        diaChi,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SuaNXBAsync(int id, string ten, string diaChi, string email) {
            this.SuaNXBAsync(id, ten, diaChi, email, null);
        }
        
        /// <remarks/>
        public void SuaNXBAsync(int id, string ten, string diaChi, string email, object userState) {
            if ((this.SuaNXBOperationCompleted == null)) {
                this.SuaNXBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuaNXBOperationCompleted);
            }
            this.InvokeAsync("SuaNXB", new object[] {
                        id,
                        ten,
                        diaChi,
                        email}, this.SuaNXBOperationCompleted, userState);
        }
        
        private void OnSuaNXBOperationCompleted(object arg) {
            if ((this.SuaNXBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuaNXBCompleted(this, new SuaNXBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaNXB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XoaNXB(int id) {
            object[] results = this.Invoke("XoaNXB", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XoaNXBAsync(int id) {
            this.XoaNXBAsync(id, null);
        }
        
        /// <remarks/>
        public void XoaNXBAsync(int id, object userState) {
            if ((this.XoaNXBOperationCompleted == null)) {
                this.XoaNXBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaNXBOperationCompleted);
            }
            this.InvokeAsync("XoaNXB", new object[] {
                        id}, this.XoaNXBOperationCompleted, userState);
        }
        
        private void OnXoaNXBOperationCompleted(object arg) {
            if ((this.XoaNXBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaNXBCompleted(this, new XoaNXBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimKiemNXB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TimKiemNXB(string timkiem) {
            object[] results = this.Invoke("TimKiemNXB", new object[] {
                        timkiem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimKiemNXBAsync(string timkiem) {
            this.TimKiemNXBAsync(timkiem, null);
        }
        
        /// <remarks/>
        public void TimKiemNXBAsync(string timkiem, object userState) {
            if ((this.TimKiemNXBOperationCompleted == null)) {
                this.TimKiemNXBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimKiemNXBOperationCompleted);
            }
            this.InvokeAsync("TimKiemNXB", new object[] {
                        timkiem}, this.TimKiemNXBOperationCompleted, userState);
        }
        
        private void OnTimKiemNXBOperationCompleted(object arg) {
            if ((this.TimKiemNXBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimKiemNXBCompleted(this, new TimKiemNXBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayDanhSachTacGia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LayDanhSachTacGia() {
            object[] results = this.Invoke("LayDanhSachTacGia", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LayDanhSachTacGiaAsync() {
            this.LayDanhSachTacGiaAsync(null);
        }
        
        /// <remarks/>
        public void LayDanhSachTacGiaAsync(object userState) {
            if ((this.LayDanhSachTacGiaOperationCompleted == null)) {
                this.LayDanhSachTacGiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayDanhSachTacGiaOperationCompleted);
            }
            this.InvokeAsync("LayDanhSachTacGia", new object[0], this.LayDanhSachTacGiaOperationCompleted, userState);
        }
        
        private void OnLayDanhSachTacGiaOperationCompleted(object arg) {
            if ((this.LayDanhSachTacGiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayDanhSachTacGiaCompleted(this, new LayDanhSachTacGiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemTG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ThemTG(string ten, string vaitro, string email) {
            object[] results = this.Invoke("ThemTG", new object[] {
                        ten,
                        vaitro,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ThemTGAsync(string ten, string vaitro, string email) {
            this.ThemTGAsync(ten, vaitro, email, null);
        }
        
        /// <remarks/>
        public void ThemTGAsync(string ten, string vaitro, string email, object userState) {
            if ((this.ThemTGOperationCompleted == null)) {
                this.ThemTGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemTGOperationCompleted);
            }
            this.InvokeAsync("ThemTG", new object[] {
                        ten,
                        vaitro,
                        email}, this.ThemTGOperationCompleted, userState);
        }
        
        private void OnThemTGOperationCompleted(object arg) {
            if ((this.ThemTGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemTGCompleted(this, new ThemTGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SuaTG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SuaTG(int id, string ten, string vaitro, string email) {
            object[] results = this.Invoke("SuaTG", new object[] {
                        id,
                        ten,
                        vaitro,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SuaTGAsync(int id, string ten, string vaitro, string email) {
            this.SuaTGAsync(id, ten, vaitro, email, null);
        }
        
        /// <remarks/>
        public void SuaTGAsync(int id, string ten, string vaitro, string email, object userState) {
            if ((this.SuaTGOperationCompleted == null)) {
                this.SuaTGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuaTGOperationCompleted);
            }
            this.InvokeAsync("SuaTG", new object[] {
                        id,
                        ten,
                        vaitro,
                        email}, this.SuaTGOperationCompleted, userState);
        }
        
        private void OnSuaTGOperationCompleted(object arg) {
            if ((this.SuaTGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuaTGCompleted(this, new SuaTGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaTG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XoaTG(int id) {
            object[] results = this.Invoke("XoaTG", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XoaTGAsync(int id) {
            this.XoaTGAsync(id, null);
        }
        
        /// <remarks/>
        public void XoaTGAsync(int id, object userState) {
            if ((this.XoaTGOperationCompleted == null)) {
                this.XoaTGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaTGOperationCompleted);
            }
            this.InvokeAsync("XoaTG", new object[] {
                        id}, this.XoaTGOperationCompleted, userState);
        }
        
        private void OnXoaTGOperationCompleted(object arg) {
            if ((this.XoaTGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaTGCompleted(this, new XoaTGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimKiemTG", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TimKiemTG(string timkiem) {
            object[] results = this.Invoke("TimKiemTG", new object[] {
                        timkiem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimKiemTGAsync(string timkiem) {
            this.TimKiemTGAsync(timkiem, null);
        }
        
        /// <remarks/>
        public void TimKiemTGAsync(string timkiem, object userState) {
            if ((this.TimKiemTGOperationCompleted == null)) {
                this.TimKiemTGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimKiemTGOperationCompleted);
            }
            this.InvokeAsync("TimKiemTG", new object[] {
                        timkiem}, this.TimKiemTGOperationCompleted, userState);
        }
        
        private void OnTimKiemTGOperationCompleted(object arg) {
            if ((this.TimKiemTGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimKiemTGCompleted(this, new TimKiemTGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PhieuMuon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PhieuMuon(string id) {
            object[] results = this.Invoke("PhieuMuon", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PhieuMuonAsync(string id) {
            this.PhieuMuonAsync(id, null);
        }
        
        /// <remarks/>
        public void PhieuMuonAsync(string id, object userState) {
            if ((this.PhieuMuonOperationCompleted == null)) {
                this.PhieuMuonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPhieuMuonOperationCompleted);
            }
            this.InvokeAsync("PhieuMuon", new object[] {
                        id}, this.PhieuMuonOperationCompleted, userState);
        }
        
        private void OnPhieuMuonOperationCompleted(object arg) {
            if ((this.PhieuMuonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PhieuMuonCompleted(this, new PhieuMuonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TinhTrangMuon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TinhTrangMuon(string id) {
            object[] results = this.Invoke("TinhTrangMuon", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TinhTrangMuonAsync(string id) {
            this.TinhTrangMuonAsync(id, null);
        }
        
        /// <remarks/>
        public void TinhTrangMuonAsync(string id, object userState) {
            if ((this.TinhTrangMuonOperationCompleted == null)) {
                this.TinhTrangMuonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTinhTrangMuonOperationCompleted);
            }
            this.InvokeAsync("TinhTrangMuon", new object[] {
                        id}, this.TinhTrangMuonOperationCompleted, userState);
        }
        
        private void OnTinhTrangMuonOperationCompleted(object arg) {
            if ((this.TinhTrangMuonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TinhTrangMuonCompleted(this, new TinhTrangMuonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayTenBanDoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LayTenBanDoc(string id) {
            object[] results = this.Invoke("LayTenBanDoc", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LayTenBanDocAsync(string id) {
            this.LayTenBanDocAsync(id, null);
        }
        
        /// <remarks/>
        public void LayTenBanDocAsync(string id, object userState) {
            if ((this.LayTenBanDocOperationCompleted == null)) {
                this.LayTenBanDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayTenBanDocOperationCompleted);
            }
            this.InvokeAsync("LayTenBanDoc", new object[] {
                        id}, this.LayTenBanDocOperationCompleted, userState);
        }
        
        private void OnLayTenBanDocOperationCompleted(object arg) {
            if ((this.LayTenBanDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayTenBanDocCompleted(this, new LayTenBanDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LayMaBanDoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int LayMaBanDoc(string id) {
            object[] results = this.Invoke("LayMaBanDoc", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LayMaBanDocAsync(string id) {
            this.LayMaBanDocAsync(id, null);
        }
        
        /// <remarks/>
        public void LayMaBanDocAsync(string id, object userState) {
            if ((this.LayMaBanDocOperationCompleted == null)) {
                this.LayMaBanDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLayMaBanDocOperationCompleted);
            }
            this.InvokeAsync("LayMaBanDoc", new object[] {
                        id}, this.LayMaBanDocOperationCompleted, userState);
        }
        
        private void OnLayMaBanDocOperationCompleted(object arg) {
            if ((this.LayMaBanDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LayMaBanDocCompleted(this, new LayMaBanDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/KTPhieuMuon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool KTPhieuMuon(string id) {
            object[] results = this.Invoke("KTPhieuMuon", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void KTPhieuMuonAsync(string id) {
            this.KTPhieuMuonAsync(id, null);
        }
        
        /// <remarks/>
        public void KTPhieuMuonAsync(string id, object userState) {
            if ((this.KTPhieuMuonOperationCompleted == null)) {
                this.KTPhieuMuonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKTPhieuMuonOperationCompleted);
            }
            this.InvokeAsync("KTPhieuMuon", new object[] {
                        id}, this.KTPhieuMuonOperationCompleted, userState);
        }
        
        private void OnKTPhieuMuonOperationCompleted(object arg) {
            if ((this.KTPhieuMuonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.KTPhieuMuonCompleted(this, new KTPhieuMuonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DangNhap", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DangNhap(string ten, string matkhau) {
            object[] results = this.Invoke("DangNhap", new object[] {
                        ten,
                        matkhau});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DangNhapAsync(string ten, string matkhau) {
            this.DangNhapAsync(ten, matkhau, null);
        }
        
        /// <remarks/>
        public void DangNhapAsync(string ten, string matkhau, object userState) {
            if ((this.DangNhapOperationCompleted == null)) {
                this.DangNhapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDangNhapOperationCompleted);
            }
            this.InvokeAsync("DangNhap", new object[] {
                        ten,
                        matkhau}, this.DangNhapOperationCompleted, userState);
        }
        
        private void OnDangNhapOperationCompleted(object arg) {
            if ((this.DangNhapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DangNhapCompleted(this, new DangNhapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LayDanhSachNXBCompletedEventHandler(object sender, LayDanhSachNXBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDanhSachNXBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDanhSachNXBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ThemNXBCompletedEventHandler(object sender, ThemNXBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemNXBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemNXBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SuaNXBCompletedEventHandler(object sender, SuaNXBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuaNXBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuaNXBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void XoaNXBCompletedEventHandler(object sender, XoaNXBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaNXBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaNXBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TimKiemNXBCompletedEventHandler(object sender, TimKiemNXBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimKiemNXBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimKiemNXBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LayDanhSachTacGiaCompletedEventHandler(object sender, LayDanhSachTacGiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayDanhSachTacGiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayDanhSachTacGiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ThemTGCompletedEventHandler(object sender, ThemTGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemTGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemTGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SuaTGCompletedEventHandler(object sender, SuaTGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuaTGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SuaTGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void XoaTGCompletedEventHandler(object sender, XoaTGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaTGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaTGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TimKiemTGCompletedEventHandler(object sender, TimKiemTGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimKiemTGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimKiemTGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PhieuMuonCompletedEventHandler(object sender, PhieuMuonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PhieuMuonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PhieuMuonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TinhTrangMuonCompletedEventHandler(object sender, TinhTrangMuonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TinhTrangMuonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TinhTrangMuonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LayTenBanDocCompletedEventHandler(object sender, LayTenBanDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayTenBanDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayTenBanDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LayMaBanDocCompletedEventHandler(object sender, LayMaBanDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LayMaBanDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LayMaBanDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void KTPhieuMuonCompletedEventHandler(object sender, KTPhieuMuonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KTPhieuMuonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal KTPhieuMuonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DangNhapCompletedEventHandler(object sender, DangNhapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DangNhapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DangNhapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591