//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Clients_ThuVien.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceQLThuVienSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceQLThuVien : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback QLSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback DemChuDeOperationCompleted;
        
        private System.Threading.SendOrPostCallback demslchudeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DanhSachBanDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemBanDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimBanDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaBanDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhatBanDocOperationCompleted;
        
        private System.Threading.SendOrPostCallback DanhSachDauSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemDauSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimDauSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaDauSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhatDauSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback DanhSachCuonSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback ThemCuonSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback TimCuonSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback XoaCuonSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback CapNhatCuonSachOperationCompleted;
        
        private System.Threading.SendOrPostCallback danhSachNhaXuatBanOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceQLThuVien() {
            this.Url = global::Clients_ThuVien.Properties.Settings.Default.Clients_ThuVien_localhost_ServiceQLThuVien;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event QLSachCompletedEventHandler QLSachCompleted;
        
        /// <remarks/>
        public event DemChuDeCompletedEventHandler DemChuDeCompleted;
        
        /// <remarks/>
        public event demslchudeCompletedEventHandler demslchudeCompleted;
        
        /// <remarks/>
        public event DanhSachBanDocCompletedEventHandler DanhSachBanDocCompleted;
        
        /// <remarks/>
        public event ThemBanDocCompletedEventHandler ThemBanDocCompleted;
        
        /// <remarks/>
        public event TimBanDocCompletedEventHandler TimBanDocCompleted;
        
        /// <remarks/>
        public event XoaBanDocCompletedEventHandler XoaBanDocCompleted;
        
        /// <remarks/>
        public event CapNhatBanDocCompletedEventHandler CapNhatBanDocCompleted;
        
        /// <remarks/>
        public event DanhSachDauSachCompletedEventHandler DanhSachDauSachCompleted;
        
        /// <remarks/>
        public event ThemDauSachCompletedEventHandler ThemDauSachCompleted;
        
        /// <remarks/>
        public event TimDauSachCompletedEventHandler TimDauSachCompleted;
        
        /// <remarks/>
        public event XoaDauSachCompletedEventHandler XoaDauSachCompleted;
        
        /// <remarks/>
        public event CapNhatDauSachCompletedEventHandler CapNhatDauSachCompleted;
        
        /// <remarks/>
        public event DanhSachCuonSachCompletedEventHandler DanhSachCuonSachCompleted;
        
        /// <remarks/>
        public event ThemCuonSachCompletedEventHandler ThemCuonSachCompleted;
        
        /// <remarks/>
        public event TimCuonSachCompletedEventHandler TimCuonSachCompleted;
        
        /// <remarks/>
        public event XoaCuonSachCompletedEventHandler XoaCuonSachCompleted;
        
        /// <remarks/>
        public event CapNhatCuonSachCompletedEventHandler CapNhatCuonSachCompleted;
        
        /// <remarks/>
        public event danhSachNhaXuatBanCompletedEventHandler danhSachNhaXuatBanCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QLSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QLSach(string tencd) {
            object[] results = this.Invoke("QLSach", new object[] {
                        tencd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QLSachAsync(string tencd) {
            this.QLSachAsync(tencd, null);
        }
        
        /// <remarks/>
        public void QLSachAsync(string tencd, object userState) {
            if ((this.QLSachOperationCompleted == null)) {
                this.QLSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQLSachOperationCompleted);
            }
            this.InvokeAsync("QLSach", new object[] {
                        tencd}, this.QLSachOperationCompleted, userState);
        }
        
        private void OnQLSachOperationCompleted(object arg) {
            if ((this.QLSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QLSachCompleted(this, new QLSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DemChuDe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DemChuDe() {
            object[] results = this.Invoke("DemChuDe", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DemChuDeAsync() {
            this.DemChuDeAsync(null);
        }
        
        /// <remarks/>
        public void DemChuDeAsync(object userState) {
            if ((this.DemChuDeOperationCompleted == null)) {
                this.DemChuDeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDemChuDeOperationCompleted);
            }
            this.InvokeAsync("DemChuDe", new object[0], this.DemChuDeOperationCompleted, userState);
        }
        
        private void OnDemChuDeOperationCompleted(object arg) {
            if ((this.DemChuDeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DemChuDeCompleted(this, new DemChuDeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/demslchude", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int demslchude() {
            object[] results = this.Invoke("demslchude", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void demslchudeAsync() {
            this.demslchudeAsync(null);
        }
        
        /// <remarks/>
        public void demslchudeAsync(object userState) {
            if ((this.demslchudeOperationCompleted == null)) {
                this.demslchudeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndemslchudeOperationCompleted);
            }
            this.InvokeAsync("demslchude", new object[0], this.demslchudeOperationCompleted, userState);
        }
        
        private void OndemslchudeOperationCompleted(object arg) {
            if ((this.demslchudeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.demslchudeCompleted(this, new demslchudeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DanhSachBanDoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DanhSachBanDoc() {
            object[] results = this.Invoke("DanhSachBanDoc", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DanhSachBanDocAsync() {
            this.DanhSachBanDocAsync(null);
        }
        
        /// <remarks/>
        public void DanhSachBanDocAsync(object userState) {
            if ((this.DanhSachBanDocOperationCompleted == null)) {
                this.DanhSachBanDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanhSachBanDocOperationCompleted);
            }
            this.InvokeAsync("DanhSachBanDoc", new object[0], this.DanhSachBanDocOperationCompleted, userState);
        }
        
        private void OnDanhSachBanDocOperationCompleted(object arg) {
            if ((this.DanhSachBanDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanhSachBanDocCompleted(this, new DanhSachBanDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemBanDoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ThemBanDoc(string HoVaTen, string SoDienThoai, string DiaChi, bool GioiTinh, System.DateTime NgaySinh) {
            object[] results = this.Invoke("ThemBanDoc", new object[] {
                        HoVaTen,
                        SoDienThoai,
                        DiaChi,
                        GioiTinh,
                        NgaySinh});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ThemBanDocAsync(string HoVaTen, string SoDienThoai, string DiaChi, bool GioiTinh, System.DateTime NgaySinh) {
            this.ThemBanDocAsync(HoVaTen, SoDienThoai, DiaChi, GioiTinh, NgaySinh, null);
        }
        
        /// <remarks/>
        public void ThemBanDocAsync(string HoVaTen, string SoDienThoai, string DiaChi, bool GioiTinh, System.DateTime NgaySinh, object userState) {
            if ((this.ThemBanDocOperationCompleted == null)) {
                this.ThemBanDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemBanDocOperationCompleted);
            }
            this.InvokeAsync("ThemBanDoc", new object[] {
                        HoVaTen,
                        SoDienThoai,
                        DiaChi,
                        GioiTinh,
                        NgaySinh}, this.ThemBanDocOperationCompleted, userState);
        }
        
        private void OnThemBanDocOperationCompleted(object arg) {
            if ((this.ThemBanDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemBanDocCompleted(this, new ThemBanDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimBanDoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TimBanDoc(string ChuoiTimKiem) {
            object[] results = this.Invoke("TimBanDoc", new object[] {
                        ChuoiTimKiem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimBanDocAsync(string ChuoiTimKiem) {
            this.TimBanDocAsync(ChuoiTimKiem, null);
        }
        
        /// <remarks/>
        public void TimBanDocAsync(string ChuoiTimKiem, object userState) {
            if ((this.TimBanDocOperationCompleted == null)) {
                this.TimBanDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimBanDocOperationCompleted);
            }
            this.InvokeAsync("TimBanDoc", new object[] {
                        ChuoiTimKiem}, this.TimBanDocOperationCompleted, userState);
        }
        
        private void OnTimBanDocOperationCompleted(object arg) {
            if ((this.TimBanDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimBanDocCompleted(this, new TimBanDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaBanDoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int XoaBanDoc(int id) {
            object[] results = this.Invoke("XoaBanDoc", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void XoaBanDocAsync(int id) {
            this.XoaBanDocAsync(id, null);
        }
        
        /// <remarks/>
        public void XoaBanDocAsync(int id, object userState) {
            if ((this.XoaBanDocOperationCompleted == null)) {
                this.XoaBanDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaBanDocOperationCompleted);
            }
            this.InvokeAsync("XoaBanDoc", new object[] {
                        id}, this.XoaBanDocOperationCompleted, userState);
        }
        
        private void OnXoaBanDocOperationCompleted(object arg) {
            if ((this.XoaBanDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaBanDocCompleted(this, new XoaBanDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CapNhatBanDoc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CapNhatBanDoc(int Id, string HoVaTen, string SoDienThoai, string DiaChi, bool GioiTinh, System.DateTime NgaySinh) {
            object[] results = this.Invoke("CapNhatBanDoc", new object[] {
                        Id,
                        HoVaTen,
                        SoDienThoai,
                        DiaChi,
                        GioiTinh,
                        NgaySinh});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhatBanDocAsync(int Id, string HoVaTen, string SoDienThoai, string DiaChi, bool GioiTinh, System.DateTime NgaySinh) {
            this.CapNhatBanDocAsync(Id, HoVaTen, SoDienThoai, DiaChi, GioiTinh, NgaySinh, null);
        }
        
        /// <remarks/>
        public void CapNhatBanDocAsync(int Id, string HoVaTen, string SoDienThoai, string DiaChi, bool GioiTinh, System.DateTime NgaySinh, object userState) {
            if ((this.CapNhatBanDocOperationCompleted == null)) {
                this.CapNhatBanDocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhatBanDocOperationCompleted);
            }
            this.InvokeAsync("CapNhatBanDoc", new object[] {
                        Id,
                        HoVaTen,
                        SoDienThoai,
                        DiaChi,
                        GioiTinh,
                        NgaySinh}, this.CapNhatBanDocOperationCompleted, userState);
        }
        
        private void OnCapNhatBanDocOperationCompleted(object arg) {
            if ((this.CapNhatBanDocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhatBanDocCompleted(this, new CapNhatBanDocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DanhSachDauSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DanhSachDauSach() {
            object[] results = this.Invoke("DanhSachDauSach", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DanhSachDauSachAsync() {
            this.DanhSachDauSachAsync(null);
        }
        
        /// <remarks/>
        public void DanhSachDauSachAsync(object userState) {
            if ((this.DanhSachDauSachOperationCompleted == null)) {
                this.DanhSachDauSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanhSachDauSachOperationCompleted);
            }
            this.InvokeAsync("DanhSachDauSach", new object[0], this.DanhSachDauSachOperationCompleted, userState);
        }
        
        private void OnDanhSachDauSachOperationCompleted(object arg) {
            if ((this.DanhSachDauSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanhSachDauSachCompleted(this, new DanhSachDauSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemDauSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ThemDauSach(string ISBN, string TenDauSach, string NamXuatBan, string KichThuoc, string NgonNgu, int TrongLuong, double GiaBia, int SoTrang, int SoNgayToiDaMuon, string TenNhaXuatBan) {
            object[] results = this.Invoke("ThemDauSach", new object[] {
                        ISBN,
                        TenDauSach,
                        NamXuatBan,
                        KichThuoc,
                        NgonNgu,
                        TrongLuong,
                        GiaBia,
                        SoTrang,
                        SoNgayToiDaMuon,
                        TenNhaXuatBan});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ThemDauSachAsync(string ISBN, string TenDauSach, string NamXuatBan, string KichThuoc, string NgonNgu, int TrongLuong, double GiaBia, int SoTrang, int SoNgayToiDaMuon, string TenNhaXuatBan) {
            this.ThemDauSachAsync(ISBN, TenDauSach, NamXuatBan, KichThuoc, NgonNgu, TrongLuong, GiaBia, SoTrang, SoNgayToiDaMuon, TenNhaXuatBan, null);
        }
        
        /// <remarks/>
        public void ThemDauSachAsync(string ISBN, string TenDauSach, string NamXuatBan, string KichThuoc, string NgonNgu, int TrongLuong, double GiaBia, int SoTrang, int SoNgayToiDaMuon, string TenNhaXuatBan, object userState) {
            if ((this.ThemDauSachOperationCompleted == null)) {
                this.ThemDauSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemDauSachOperationCompleted);
            }
            this.InvokeAsync("ThemDauSach", new object[] {
                        ISBN,
                        TenDauSach,
                        NamXuatBan,
                        KichThuoc,
                        NgonNgu,
                        TrongLuong,
                        GiaBia,
                        SoTrang,
                        SoNgayToiDaMuon,
                        TenNhaXuatBan}, this.ThemDauSachOperationCompleted, userState);
        }
        
        private void OnThemDauSachOperationCompleted(object arg) {
            if ((this.ThemDauSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemDauSachCompleted(this, new ThemDauSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimDauSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TimDauSach(string ChuoiTimKiem) {
            object[] results = this.Invoke("TimDauSach", new object[] {
                        ChuoiTimKiem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimDauSachAsync(string ChuoiTimKiem) {
            this.TimDauSachAsync(ChuoiTimKiem, null);
        }
        
        /// <remarks/>
        public void TimDauSachAsync(string ChuoiTimKiem, object userState) {
            if ((this.TimDauSachOperationCompleted == null)) {
                this.TimDauSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimDauSachOperationCompleted);
            }
            this.InvokeAsync("TimDauSach", new object[] {
                        ChuoiTimKiem}, this.TimDauSachOperationCompleted, userState);
        }
        
        private void OnTimDauSachOperationCompleted(object arg) {
            if ((this.TimDauSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimDauSachCompleted(this, new TimDauSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaDauSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int XoaDauSach(int id) {
            object[] results = this.Invoke("XoaDauSach", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void XoaDauSachAsync(int id) {
            this.XoaDauSachAsync(id, null);
        }
        
        /// <remarks/>
        public void XoaDauSachAsync(int id, object userState) {
            if ((this.XoaDauSachOperationCompleted == null)) {
                this.XoaDauSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaDauSachOperationCompleted);
            }
            this.InvokeAsync("XoaDauSach", new object[] {
                        id}, this.XoaDauSachOperationCompleted, userState);
        }
        
        private void OnXoaDauSachOperationCompleted(object arg) {
            if ((this.XoaDauSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaDauSachCompleted(this, new XoaDauSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CapNhatDauSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CapNhatDauSach(int Id, string ISBN, string TenDauSach, string NamXuatBan, string KichThuoc, string NgonNgu, int TrongLuong, double GiaBia, int SoTrang, int SoNgayToiDaMuon, string TenNhaXuatBan) {
            object[] results = this.Invoke("CapNhatDauSach", new object[] {
                        Id,
                        ISBN,
                        TenDauSach,
                        NamXuatBan,
                        KichThuoc,
                        NgonNgu,
                        TrongLuong,
                        GiaBia,
                        SoTrang,
                        SoNgayToiDaMuon,
                        TenNhaXuatBan});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhatDauSachAsync(int Id, string ISBN, string TenDauSach, string NamXuatBan, string KichThuoc, string NgonNgu, int TrongLuong, double GiaBia, int SoTrang, int SoNgayToiDaMuon, string TenNhaXuatBan) {
            this.CapNhatDauSachAsync(Id, ISBN, TenDauSach, NamXuatBan, KichThuoc, NgonNgu, TrongLuong, GiaBia, SoTrang, SoNgayToiDaMuon, TenNhaXuatBan, null);
        }
        
        /// <remarks/>
        public void CapNhatDauSachAsync(int Id, string ISBN, string TenDauSach, string NamXuatBan, string KichThuoc, string NgonNgu, int TrongLuong, double GiaBia, int SoTrang, int SoNgayToiDaMuon, string TenNhaXuatBan, object userState) {
            if ((this.CapNhatDauSachOperationCompleted == null)) {
                this.CapNhatDauSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhatDauSachOperationCompleted);
            }
            this.InvokeAsync("CapNhatDauSach", new object[] {
                        Id,
                        ISBN,
                        TenDauSach,
                        NamXuatBan,
                        KichThuoc,
                        NgonNgu,
                        TrongLuong,
                        GiaBia,
                        SoTrang,
                        SoNgayToiDaMuon,
                        TenNhaXuatBan}, this.CapNhatDauSachOperationCompleted, userState);
        }
        
        private void OnCapNhatDauSachOperationCompleted(object arg) {
            if ((this.CapNhatDauSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhatDauSachCompleted(this, new CapNhatDauSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DanhSachCuonSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DanhSachCuonSach() {
            object[] results = this.Invoke("DanhSachCuonSach", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DanhSachCuonSachAsync() {
            this.DanhSachCuonSachAsync(null);
        }
        
        /// <remarks/>
        public void DanhSachCuonSachAsync(object userState) {
            if ((this.DanhSachCuonSachOperationCompleted == null)) {
                this.DanhSachCuonSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDanhSachCuonSachOperationCompleted);
            }
            this.InvokeAsync("DanhSachCuonSach", new object[0], this.DanhSachCuonSachOperationCompleted, userState);
        }
        
        private void OnDanhSachCuonSachOperationCompleted(object arg) {
            if ((this.DanhSachCuonSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DanhSachCuonSachCompleted(this, new DanhSachCuonSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ThemCuonSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ThemCuonSach(string ISBN, string SoDanhNhan) {
            object[] results = this.Invoke("ThemCuonSach", new object[] {
                        ISBN,
                        SoDanhNhan});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ThemCuonSachAsync(string ISBN, string SoDanhNhan) {
            this.ThemCuonSachAsync(ISBN, SoDanhNhan, null);
        }
        
        /// <remarks/>
        public void ThemCuonSachAsync(string ISBN, string SoDanhNhan, object userState) {
            if ((this.ThemCuonSachOperationCompleted == null)) {
                this.ThemCuonSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnThemCuonSachOperationCompleted);
            }
            this.InvokeAsync("ThemCuonSach", new object[] {
                        ISBN,
                        SoDanhNhan}, this.ThemCuonSachOperationCompleted, userState);
        }
        
        private void OnThemCuonSachOperationCompleted(object arg) {
            if ((this.ThemCuonSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ThemCuonSachCompleted(this, new ThemCuonSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TimCuonSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TimCuonSach(string ChuoiTimKiem) {
            object[] results = this.Invoke("TimCuonSach", new object[] {
                        ChuoiTimKiem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TimCuonSachAsync(string ChuoiTimKiem) {
            this.TimCuonSachAsync(ChuoiTimKiem, null);
        }
        
        /// <remarks/>
        public void TimCuonSachAsync(string ChuoiTimKiem, object userState) {
            if ((this.TimCuonSachOperationCompleted == null)) {
                this.TimCuonSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTimCuonSachOperationCompleted);
            }
            this.InvokeAsync("TimCuonSach", new object[] {
                        ChuoiTimKiem}, this.TimCuonSachOperationCompleted, userState);
        }
        
        private void OnTimCuonSachOperationCompleted(object arg) {
            if ((this.TimCuonSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TimCuonSachCompleted(this, new TimCuonSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XoaCuonSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int XoaCuonSach(int id) {
            object[] results = this.Invoke("XoaCuonSach", new object[] {
                        id});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void XoaCuonSachAsync(int id) {
            this.XoaCuonSachAsync(id, null);
        }
        
        /// <remarks/>
        public void XoaCuonSachAsync(int id, object userState) {
            if ((this.XoaCuonSachOperationCompleted == null)) {
                this.XoaCuonSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXoaCuonSachOperationCompleted);
            }
            this.InvokeAsync("XoaCuonSach", new object[] {
                        id}, this.XoaCuonSachOperationCompleted, userState);
        }
        
        private void OnXoaCuonSachOperationCompleted(object arg) {
            if ((this.XoaCuonSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XoaCuonSachCompleted(this, new XoaCuonSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CapNhatCuonSach", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CapNhatCuonSach(int Id, string SoDanhNhan, string ISBN) {
            object[] results = this.Invoke("CapNhatCuonSach", new object[] {
                        Id,
                        SoDanhNhan,
                        ISBN});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CapNhatCuonSachAsync(int Id, string SoDanhNhan, string ISBN) {
            this.CapNhatCuonSachAsync(Id, SoDanhNhan, ISBN, null);
        }
        
        /// <remarks/>
        public void CapNhatCuonSachAsync(int Id, string SoDanhNhan, string ISBN, object userState) {
            if ((this.CapNhatCuonSachOperationCompleted == null)) {
                this.CapNhatCuonSachOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCapNhatCuonSachOperationCompleted);
            }
            this.InvokeAsync("CapNhatCuonSach", new object[] {
                        Id,
                        SoDanhNhan,
                        ISBN}, this.CapNhatCuonSachOperationCompleted, userState);
        }
        
        private void OnCapNhatCuonSachOperationCompleted(object arg) {
            if ((this.CapNhatCuonSachCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CapNhatCuonSachCompleted(this, new CapNhatCuonSachCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/danhSachNhaXuatBan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string danhSachNhaXuatBan() {
            object[] results = this.Invoke("danhSachNhaXuatBan", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void danhSachNhaXuatBanAsync() {
            this.danhSachNhaXuatBanAsync(null);
        }
        
        /// <remarks/>
        public void danhSachNhaXuatBanAsync(object userState) {
            if ((this.danhSachNhaXuatBanOperationCompleted == null)) {
                this.danhSachNhaXuatBanOperationCompleted = new System.Threading.SendOrPostCallback(this.OndanhSachNhaXuatBanOperationCompleted);
            }
            this.InvokeAsync("danhSachNhaXuatBan", new object[0], this.danhSachNhaXuatBanOperationCompleted, userState);
        }
        
        private void OndanhSachNhaXuatBanOperationCompleted(object arg) {
            if ((this.danhSachNhaXuatBanCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.danhSachNhaXuatBanCompleted(this, new danhSachNhaXuatBanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void QLSachCompletedEventHandler(object sender, QLSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QLSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QLSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DemChuDeCompletedEventHandler(object sender, DemChuDeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DemChuDeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DemChuDeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void demslchudeCompletedEventHandler(object sender, demslchudeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class demslchudeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal demslchudeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DanhSachBanDocCompletedEventHandler(object sender, DanhSachBanDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanhSachBanDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanhSachBanDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ThemBanDocCompletedEventHandler(object sender, ThemBanDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemBanDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemBanDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TimBanDocCompletedEventHandler(object sender, TimBanDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimBanDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimBanDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void XoaBanDocCompletedEventHandler(object sender, XoaBanDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaBanDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaBanDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CapNhatBanDocCompletedEventHandler(object sender, CapNhatBanDocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhatBanDocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhatBanDocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DanhSachDauSachCompletedEventHandler(object sender, DanhSachDauSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanhSachDauSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanhSachDauSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ThemDauSachCompletedEventHandler(object sender, ThemDauSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemDauSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemDauSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TimDauSachCompletedEventHandler(object sender, TimDauSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimDauSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimDauSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void XoaDauSachCompletedEventHandler(object sender, XoaDauSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaDauSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaDauSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CapNhatDauSachCompletedEventHandler(object sender, CapNhatDauSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhatDauSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhatDauSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DanhSachCuonSachCompletedEventHandler(object sender, DanhSachCuonSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DanhSachCuonSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DanhSachCuonSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ThemCuonSachCompletedEventHandler(object sender, ThemCuonSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ThemCuonSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ThemCuonSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void TimCuonSachCompletedEventHandler(object sender, TimCuonSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimCuonSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TimCuonSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void XoaCuonSachCompletedEventHandler(object sender, XoaCuonSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XoaCuonSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XoaCuonSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CapNhatCuonSachCompletedEventHandler(object sender, CapNhatCuonSachCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CapNhatCuonSachCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CapNhatCuonSachCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void danhSachNhaXuatBanCompletedEventHandler(object sender, danhSachNhaXuatBanCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class danhSachNhaXuatBanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal danhSachNhaXuatBanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591